### ISSUE TITLE
Default tour route

### ISSUE THREAD

**Issue by kalenpatton** [kalenpatton/gt-sustainability-tour#7]
SCENARIO: Acquiring most efficient route when already selected
Given the user already has the default route selected,
When the user presses the “default route” button,
Then a notification informs the user that they already have the default route selected and nothing happens.

SCENARIO: Acquiring most efficient route when user has modified route
Given the user has a personalized tour selected,
When the user presses the “default route” button,
Then the current route is replaced with the default one.

**Comment by bldover** [comment]
New field on location table for stop order
