### ISSUE TITLE
As a user, I want to be able to filter the locations so I can narrow down the options based on specific categories that I choose.

### ISSUE THREAD

**Issue by kalenpatton** [kalenpatton/gt-sustainability-tour#8]
SCENARIO: Adding a single filter when no filter currently enabled
Given there is currently no filter in place,
When the user selects one location filter,
Then the map updates to only show locations with that filter.

SCENARIO: Adding multiple filters when no filter currently enabled
Given there is currently no filter in place,
When the user selects multiple filters,
Then the map updates to only show locations matching those filters.

SCENARIO: Adding filter when filter(s) already selected
Given there is already at least one filter selected,
When the user selects another filter,
Then the new filter is added to the old ones and only locations matching the filters are shown.

SCENARIO: Removing filter with clear filter button
Given there is at least one filter selected,
When the user presses the clear filter button,
Then all filters are removed and the map reverts to show all locations.

SCENARIO: Removing filter one at a time
Given there is at least one filter selected,
When the user unselects a selected filter,
Then the map updates to not show locations matching the removed filter.

**Comment by bldover** [comment]
Reordering is way better now and far less finicky.
I'm having a bug where sometimes I can't delete a stop until I've clicked the delete button multiple times. This seems to consistently affect "The First Graduate Sculpture" location.
